const MODEL_URL='https://huggingface.co/peterhdd/pothole-detection-yolov8/resolve/main/best.onnx';
const INPUT=640, CONF=.35, IOU=.45, DETECT_EVERY=260;
let session=null, running=false, mode='idle', stream=null, gpsWatch=null, timer=null, startedAt=null, finishedAt=null, lastInfer=0, lastFrame=0;
let tracks=[], nextId=1, events=[], route=[], lastGps=null, frameCanvas=document.createElement('canvas'), frameCtx=frameCanvas.getContext('2d');
const $=id=>document.getElementById(id); const video=$('video'), overlay=$('overlay'), octx=overlay.getContext('2d');
const map=L.map('map').setView([27.7172,85.3240],13); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);
let routeLine=L.polyline([],{color:'#29d391',weight:5}).addTo(map), startMarker=null, finishMarker=null;
function setStatus(t){$('aiStatus').textContent=t} function fmtTime(d){return d?new Date(d).toLocaleString(): '—'} function fmtDur(ms){let s=Math.floor(ms/1000),m=Math.floor(s/60);s%=60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
async function loadModel(){if(session)return;setStatus('Loading AI model…');$('aiStatusDot').style.background='#ffc857'; session=await ort.InferenceSession.create(MODEL_URL,{executionProviders:['wasm']});setStatus('AI ready');$('aiStatusDot').style.background='var(--accent)'}
function letterbox(src){const c=document.createElement('canvas');c.width=INPUT;c.height=INPUT;const x=c.getContext('2d');const scale=Math.min(INPUT/src.videoWidth,INPUT/src.videoHeight);const w=Math.round(src.videoWidth*scale),h=Math.round(src.videoHeight*scale);const dx=(INPUT-w)/2,dy=(INPUT-h)/2;x.fillStyle='#000';x.fillRect(0,0,INPUT,INPUT);x.drawImage(src,dx,dy,w,h);return {canvas:c,scale,dx,dy,w,h}}
function tensorFromCanvas(c){const d=c.getContext('2d').getImageData(0,0,INPUT,INPUT).data, a=new Float32Array(3*INPUT*INPUT);for(let i=0,p=0;i<d.length;i+=4){a[p]=d[i]/255;a[INPUT*INPUT+p]=d[i+1]/255;a[2*INPUT*INPUT+p]=d[i+2]/255;p++}return new ort.Tensor('float32',a,[1,3,INPUT,INPUT])}
function iou(a,b){const x=Math.max(a[0],b[0]),y=Math.max(a[1],b[1]),r=Math.min(a[2],b[2]),bt=Math.min(a[3],b[3]);const inter=Math.max(0,r-x)*Math.max(0,bt-y);const aa=(a[2]-a[0])*(a[3]-a[1]),ab=(b[2]-b[0])*(b[3]-b[1]);return inter/(aa+ab-inter+1e-9)}
function nms(ds){ds.sort((a,b)=>b.conf-a.conf);const out=[];while(ds.length){const x=ds.shift();out.push(x);for(let i=ds.length-1;i>=0;i--)if(iou(x.box,ds[i].box)>IOU)ds.splice(i,1)}return out}
function decode(out,lb,sw,sh){let data=out.data, dims=out.dims;const c=dims[dims.length-2], n=dims[dims.length-1];let attrs, count, transposed;if(c<n){attrs=c;count=n;transposed=true}else{attrs=n;count=c;transposed=false}const get=(a,i)=>transposed?data[a*count+i]:data[i*attrs+a];let ds=[];for(let i=0;i<count;i++){const obj=get(4,i);const conf=transposed?obj:get(4,i);if(conf<CONF)continue;let cx=get(0,i),cy=get(1,i),w=get(2,i),h=get(3,i);let score=conf;let x1=(cx-w/2),y1=(cy-h/2),x2=(cx+w/2),y2=(cy+h/2);x1=(x1-lb.dx)/lb.scale;y1=(y1-lb.dy)/lb.scale;x2=(x2-lb.dx)/lb.scale;y2=(y2-lb.dy)/lb.scale;x1=Math.max(0,Math.min(sw,x1));y1=Math.max(0,Math.min(sh,y1));x2=Math.max(0,Math.min(sw,x2));y2=Math.max(0,Math.min(sh,y2));if(x2>x1&&y2>y1)ds.push({box:[x1,y1,x2,y2],conf:score})}return nms(ds)}
function severity(box,w,h){const area=((box[2]-box[0])*(box[3]-box[1]))/(w*h);return area>.065?'High':area>.025?'Medium':'Low'}
function band(c){return c>=.75?'High':c>=.5?'Medium':'Low'}
function updateTracks(dets,w,h,evidence){const used=new Set(),newTracks=[];for(const d of dets){let best=-1,bs=.3;tracks.forEach((t,i)=>{if(!used.has(i)){const v=iou(t.box,d.box);if(v>bs){bs=v;best=i}}});if(best>=0){const t=tracks[best];used.add(best);t.box=d.box;t.conf=d.conf;t.missed=0;newTracks.push(t)}else{const t={id:nextId++,box:d.box,conf:d.conf,missed:0};newTracks.push(t);const ev={id:t.id,confidence:d.conf,severity:severity(d.box,w,h),band:band(d.conf),time:new Date().toISOString(),gps:lastGps?{...lastGps}:null,image:captureEvidence(d.box,w,h)};events.push(ev);addEvidence(ev)}}tracks.forEach((t,i)=>{if(!used.has(i)){t.missed++;if(t.missed<5)newTracks.push(t)}});tracks=newTracks;renderMetrics()}
function captureEvidence(box,w,h){frameCanvas.width=w;frameCanvas.height=h;frameCtx.drawImage(video,0,0,w,h);const pad=20,x=Math.max(0,box[0]-pad),y=Math.max(0,box[1]-pad),r=Math.min(w,box[2]+pad),b=Math.min(h,box[3]+pad);const c=document.createElement('canvas');c.width=r-x;c.height=b-y;c.getContext('2d').drawImage(frameCanvas,x,y,c.width,c.height,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.78)}
function addEvidence(ev){$('evidenceCount').textContent=events.length;const card=document.createElement('div');card.className='evidence-card';card.innerHTML=`<img src="${ev.image}"><div><b>#${ev.id} · ${ev.severity} severity</b><span>${new Date(ev.time).toLocaleTimeString()} · ${Math.round(ev.confidence*100)}% AI confidence</span></div>`;const empty=$('evidence').querySelector('.empty');if(empty)empty.remove();$('evidence').prepend(card)}
function renderMetrics(){ $('count').textContent=events.length; $('highCount').textContent=events.filter(e=>e.band==='High').length; $('avgConfidence').textContent=events.length?Math.round(events.reduce((a,e)=>a+e.confidence,0)/events.length*100)+'%':'—'}
function draw(dets,w,h){const rect=video.getBoundingClientRect(), sx=rect.width/w,sy=rect.height/h;overlay.width=rect.width*devicePixelRatio;overlay.height=rect.height*devicePixelRatio;octx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);octx.clearRect(0,0,rect.width,rect.height);dets.forEach(d=>{const [x,y,r,b]=d.box;const s=severity(d.box,w,h);octx.strokeStyle=s==='High'?'#ff5c68':s==='Medium'?'#ffc857':'#39d98a';octx.lineWidth=2;octx.strokeRect(x*sx,y*sy,(r-x)*sx,(b-y)*sy);octx.fillStyle=octx.strokeStyle;octx.font='bold 12px system-ui';octx.fillText(`Pothole ${Math.round(d.conf*100)}% · ${s}`,x*sx,Math.max(14,y*sy-5))})}
async function processFrame(){if(!running||video.readyState<2)return;const now=performance.now();if(now-lastInfer<DETECT_EVERY){requestAnimationFrame(processFrame);return}lastInfer=now;const w=video.videoWidth,h=video.videoHeight;if(!w||!h){requestAnimationFrame(processFrame);return}const lb=letterbox(video), input=tensorFromCanvas(lb.canvas);const t=performance.now();const out=await session.run({[session.inputNames[0]]:input});const dets=decode(out[session.outputNames[0]],lb,w,h);updateTracks(dets,w,h,true);draw(dets,w,h);lastFrame=performance.now()-t;requestAnimationFrame(processFrame)}
function startGps(){if(!navigator.geolocation){$('gpsStatus').textContent='Unavailable';return}gpsWatch=navigator.geolocation.watchPosition(p=>{lastGps={lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy};route.push([lastGps.lat,lastGps.lon]);routeLine.setLatLngs(route);$('gpsStatus').textContent='Live';$('lastLocation').textContent=`${lastGps.lat.toFixed(6)}, ${lastGps.lon.toFixed(6)}`;if(route.length===1){map.setView(route[0],17);startMarker=L.marker(route[0]).addTo(map).bindPopup('Inspection start').openPopup()}else if(finishMarker){map.removeLayer(finishMarker);finishMarker=null}},()=>{$('gpsStatus').textContent='Permission unavailable'})}
async function startInspection(newMode){await loadModel();mode=newMode;running=true;startedAt=new Date();finishedAt=null;tracks=[];nextId=1;events=[];route=[];lastGps=null;routeLine.setLatLngs([]);if(startMarker){map.removeLayer(startMarker);startMarker=null}if(finishMarker){map.removeLayer(finishMarker);finishMarker=null}$('evidence').innerHTML='<div class="empty">Detected pothole images will appear here.</div>';$('evidenceCount').textContent='0';renderMetrics();$('startTime').textContent=fmtTime(startedAt);$('finishTime').textContent='—';$('modeBadge').textContent=newMode==='camera'?'LIVE CAMERA':'VIDEO';$('stopBtn').disabled=false;$('cameraBtn').disabled=true;$('reportPanel').classList.add('hidden');startGps();timer=setInterval(()=>{$('elapsed').textContent=fmtDur(Date.now()-startedAt)},500);video.style.display='block';$('videoPlaceholder').style.display='none';requestAnimationFrame(processFrame)}
$('cameraBtn').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();await startInspection('camera')}catch(e){alert('Camera could not start: '+e.message)}};
$('videoInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}video.srcObject=null;video.src=URL.createObjectURL(f);video.loop=false;video.onloadedmetadata=async()=>{await video.play();await startInspection('video')}};
$('stopBtn').onclick=stopInspection;
function stopInspection(){if(!running)return;running=false;finishedAt=new Date();clearInterval(timer);if(gpsWatch!==null)navigator.geolocation.clearWatch(gpsWatch);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(lastGps&&route.length)finishMarker=L.marker(route[route.length-1]).addTo(map).bindPopup('Inspection finish').openPopup();$('finishTime').textContent=fmtTime(finishedAt);$('stopBtn').disabled=true;$('cameraBtn').disabled=false;$('modeBadge').textContent='COMPLETE';$('reportPanel').classList.remove('hidden');$('reportSummary').textContent=`${events.length} unique pothole(s) detected over ${fmtDur(finishedAt-startedAt)}. The PDF includes evidence images, timestamps, GPS locations, severity estimates and route details.`;setStatus('Inspection complete');$('video').pause()}
$('downloadReport').onclick=makePdf;
function makePdf(){const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'});let y=18;doc.setFontSize(20);doc.text('RoadScan AI — Inspection Report',15,y);y+=8;doc.setFontSize(10);doc.text(`Started: ${fmtTime(startedAt)}`,15,y);y+=5;doc.text(`Finished: ${fmtTime(finishedAt)}`,15,y);y+=5;doc.text(`Duration: ${fmtDur(finishedAt-startedAt)}   |   Unique potholes: ${events.length}`,15,y);y+=8;doc.setFontSize(13);doc.text('Inspection summary',15,y);y+=6;doc.setFontSize(10);doc.text(`High AI confidence: ${events.filter(e=>e.band==='High').length}`,15,y);doc.text(`Medium AI confidence: ${events.filter(e=>e.band==='Medium').length}`,70,y);doc.text(`Low AI confidence: ${events.filter(e=>e.band==='Low').length}`,140,y);y+=10;doc.setFontSize(12);doc.text('Pothole evidence',15,y);y+=5;for(const e of events){if(y>255){doc.addPage();y=18}try{doc.addImage(e.image,'JPEG',15,y,58,38)}catch{}doc.setFontSize(9);doc.text(`#${e.id}  ${e.severity} severity  |  ${Math.round(e.confidence*100)}% AI confidence`,78,y+6);doc.text(new Date(e.time).toLocaleString(),78,y+12);doc.text(e.gps?`GPS: ${e.gps.lat.toFixed(6)}, ${e.gps.lon.toFixed(6)}`:'GPS: unavailable',78,y+18);y+=44}if(y>250){doc.addPage();y=18}doc.setFontSize(12);doc.text('Route',15,y);y+=6;doc.setFontSize(9);doc.text(`Recorded GPS points: ${route.length}`,15,y);y+=5;if(route.length){doc.text(`Start: ${route[0][0].toFixed(6)}, ${route[0][1].toFixed(6)}`,15,y);y+=5;const end=route[route.length-1];doc.text(`Finish: ${end[0].toFixed(6)}, ${end[1].toFixed(6)}`,15,y);y+=8}doc.setFontSize(8);doc.setTextColor(100);doc.text('Severity is an estimated visual classification from camera-frame size. It is not an engineering severity assessment.',15,y,{maxWidth:180});doc.save(`roadscan-inspection-${new Date().toISOString().slice(0,19).replaceAll(':','-')}.pdf`)}
window.addEventListener('beforeunload',()=>{if(stream)stream.getTracks().forEach(t=>t.stop())});
